#!/bin/bash

# ==============================================================================

# Build all test scripts
echo "Building test scripts"
output="`(catkin build --this --catkin-make-args run_tests --)`"
success=$?
if [[ $success != 0 ]]; then
    echo "$output"
    echo -e "\nBuilding test scripts failed. Output printed above."
    exit 1
fi
echo "Test scripts built without error"

# ==============================================================================

# Find out the package name and executables
current_dir="`(dirname \"$0\")`"                  # relative
current_dir="`(cd \"$current_dir\" && pwd)`"  # absolutized and normalized
catkin_pkd_dir="`( cd \"$current_dir\" && cd .. && pwd )`"
cmakelists_file_path="$catkin_pkd_dir""/CMakeLists.txt"
cmakelists_file="`(cat $cmakelists_file_path)`"
pkg_name="`(echo "$cmakelists_file" | sed -n 's/^project(\(\S*\).*)/\1/p')`"
executables="`(echo "$cmakelists_file" | sed -n 's/^\s*catkin_add_gtest(\(\S*\)/\1/p')`"

# ==============================================================================

# run all test executables one after another
all_success=1
for executable_name in $executables; do
    echo "Executing ""$executable_name"
    executable="`(catkin_find "$pkg_name" "$executable_name")`"
    $executable
    executable_success=$?
    if [[ $executable_success != 0 ]]; then
        all_success=0
    fi
    echo ""
done

echo "#######################################"
if [[ $all_success == 1 ]]; then
    echo "All tests succeeded"
else
    echo "Not all tests succeeded"
fi
echo "#######################################"
